# This program create user when given a name with comments with autogenerated password
# User will be forced to change password on first login


#!/bin/bash

# Check running as root user
if [[ $UID -ne 0 ]]
then
    echo "root access needed. Try with sudo."
    exit 1
fi

# Check if atleast one argument given for username
if [[ $# -lt 1 ]]
then
    echo "SYNTAX : sudo bash $0 Username [optional Comments]"
    exit 1
fi

# Store first argument as username
USERNAME=$1
echo "Username will be : $USERNAME"

# Remaining arguments treated as comments
shift
COMMENTS=$@
echo "Comments will be : $COMMENTS"

# Generate password
PASSWORD=$(date +%S%N)
echo "Your Password : $PASSWORD"

# Create User with directory
useradd -c "$COMMENTS" -m $USERNAME

# Check if successfully created user
if [[ $? -ne 0 ]]
then 
    echo "Sorry :( try later"
    exit 1
fi

# Set password
echo $PASSWORD | passwd --stdin $USERNAME

# Force password change on first login
passwd -e $USERNAME